export const USER_SIGNIN = 'USER_SIGNIN' // 登录成功

export const USER_SIGNOUT = 'USER_SIGNOUT' // 退出登录

export const GET_LINK_LIST_SUCCESS = 'GET_LINK_LIST_SUCCESS'
export const GET_LINK_LIST_FAILD = 'GET_LINK_LIST_FAILD'
export const REQUEST_LINK_LIST = 'REQUEST_LINK_LIST'

export const GET_SELLER_LIST_SUCCESS = 'GET_SELLER_LIST_SUCCESS'
export const GET_SELLER_LIST_FAILD = 'GET_SELLER_LIST_FAILD'
export const REQUEST_SELLER_LIST = 'REQUEST_SELLER_LIST'

export const GET_PLAYER_LIST_SUCCESS = 'GET_PLAYER_LIST_SUCCESS'
export const GET_PLAYER_LIST_FAILD = 'GET_PLAYER_LIST_FAILD'
export const REQUEST_PLAYER_LIST = 'REQUEST_PLAYER_LIST'

export const GET_ADMIN_INFO_SUCCESS = 'GET_ADMIN_INFO_SUCCESS'
export const GET_ADMIN_INFO_FAILD = 'GET_ADMIN_INFO_FAILD'
export const REQUEST_ADMIN_INFO = 'REQUEST_ADMIN_INFO'

export const GET_SELLER_INFO_SUCCESS = 'GET_SELLER_INFO_SUCCESS'
export const GET_SELLER_INFO_FAILD = 'GET_SELLER_INFO_FAILD'
export const REQUEST_SELLER_INFO = 'REQUEST_SELLER_INFO'

export const GET_SELLER_DETAILS_SUCCESS = 'GET_SELLER_DETAILS_SUCCESS'
export const GET_SELLER_DETAILS_FAILD = 'GET_SELLER_DETAILS_FAILD'
export const REQUEST_SELLER_DETAILS = 'REQUEST_SELLER_DETAILS'
export const UPDATE_SELLER_DETAILS_COIN = 'UPDATE_SELLER_DETAILS_COIN'

export const GET_PLAYER_DETAILS_SUCCESS = 'GET_PLAYER_DETAILS_SUCCESS'
export const GET_PLAYER_DETAILS_FAILD = 'GET_PLAYER_DETAILS_FAILD'
export const REQUEST_PLAYER_DETAILS = 'REQUEST_PLAYER_DETAILS'
export const REQUEST_FINSH = 'REQUEST_FINSH'
