import Vue from 'vue'
import Promise from 'bluebird'

export const wxLogin = (store, wxCode) => {
  return Vue.api.post("users/loginWithWechat",{wxCode})
    .then(res => {
      const body = res.body
      const accessToken = body.id
      const userid = body.userId
    })
    .catch(err => {
      return Promise.reject(err)
    })
}

export const getLinkList = () => {

}


export const getQuestion = () => {

  let ret = {
    data:{
      Ask:{
        id:"1",
        name:"体质自查",
        desc:"本测评为自测量表，测得是在最近一个月内，你身上是否发生如下情况，并且以自己主观感觉划分程度，每道题中有任何一个表现或症状对应即可。程度分为5个等级，分别是从不（0分）、很少（1分）、有时（2分）、经常（3分）、总是（4分）。",
        groups:[
            {
              groupId:1,
              name:"第一部分",
              questions:[
                {
                questioId:1,
                name: "肝区隐痛或不喜油腻的食品",
                selects:[
                {
                    key:"1_1_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_1_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_1_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_1_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_1_4",
                    value:"5、总是(4分)"
                }]
              },
              
              {
                questioId:2,
                name: "发脾气后很久不能平复",
                selects:[
                {
                    key:"1_2_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_2_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_2_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_2_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_2_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:3,
                name: "眼睛会干涩或有熊猫眼或容易迎风流泪",
                selects:[
                {
                    key:"1_3_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_3_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_3_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_3_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_3_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:4,
                name: "指甲有凹陷或容易脆裂或甲床苍白",
                selects:[
                {
                    key:"1_4_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_4_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_4_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_4_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_4_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:5,
                name: "感觉到口苦或喜欢吃酸的东西、喝酸的饮料",
                selects:[
                {
                    key:"1_5_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_5_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_5_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_5_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_5_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:6,
                name: "有脂肪肝或胆结石或肝囊肿或卵巢囊肿（“无”选0分，”有“按照患病严重程度填写）",
                selects:[
                {
                    key:"1_6_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_6_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_6_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_6_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_6_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:7,
                name: "感觉肢体麻木或关节僵硬",
                selects:[
                {
                    key:"1_7_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_7_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_7_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_7_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_7_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:8,
                name: "显得比同龄人衰老",
                selects:[
                {
                    key:"1_8_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_8_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_8_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_8_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_8_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:9,
                name: "手背上青筋比较多",
                selects:[
                {
                    key:"1_9_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_9_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_9_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_9_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_9_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:10,
                name: "不喜嘈杂，听噪音就精神衰弱",
                selects:[
                {
                    key:"1_10_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_10_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_10_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_10_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_10_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:11,
                name: "听不出别人的画外音，容易较真",
                selects:[
                {
                    key:"1_11_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_11_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_11_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_11_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_11_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:12,
                name: "身体的筋短，双手够不到双脚",
                selects:[
                {
                    key:"1_12_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_12_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_12_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_12_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_12_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:13,
                name: "劳累以后很容易得病",
                selects:[
                {
                    key:"1_13_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_13_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_13_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_13_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_13_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:14,
                name: "不喜欢别人开你的玩笑，听了很生气",
                selects:[
                {
                    key:"1_14_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_14_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_14_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_14_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_14_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:15,
                name: "看电影、电视容易感动得热泪盈眶",
                selects:[
                {
                    key:"1_15_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_15_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_15_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_15_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_15_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:16,
                name: "不愿原谅别人的过错",
                selects:[
                {
                    key:"1_16_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_16_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_16_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_16_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_16_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:17,
                name: "有爱熬夜的习惯",
                selects:[
                {
                    key:"1_17_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_17_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_17_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_17_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_17_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:18,
                name: "患有青光眼或晶体混浊",
                selects:[
                {
                    key:"1_18_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_18_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_18_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_18_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_18_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:19,
                name: "面部容易出油或有黄褐斑的困扰",
                selects:[
                {
                    key:"1_19_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_19_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_19_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_19_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_19_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:20,
                name: "有梦游现象或容易出现幻觉",
                selects:[
                {
                    key:"1_20_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"1_20_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"1_20_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"1_20_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"1_20_4",
                    value:"5、总是(4分)"
                }]
              }
            ],
              fen:0
            },
            {
              groupId:2,
              name:"第二部分",
              questions:[
                {
                questioId:1,
                name: "有心脏跳动过快或过慢的表现",
                selects:[
                {
                    key:"2_1_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_1_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_1_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_1_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_1_4",
                    value:"5、总是(4分)"
                }]
              },
              
              {
                questioId:2,
                name: "脸上容易长痘痘",
                selects:[
                {
                    key:"2_2_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_2_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_2_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_2_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_2_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:3,
                name: "情绪起伏较大，遇到好事容易惊喜，遇到坏事容易悲恸",
                selects:[
                {
                    key:"2_3_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_3_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_3_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_3_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_3_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:4,
                name: "容易手心、脚心、胸口发热",
                selects:[
                {
                    key:"2_4_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_4_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_4_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_4_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_4_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:5,
                name: "比一般人更容易出汗（不动皮肤微潮湿，稍动则更甚，动则汗出如水渍）",
                selects:[
                {
                    key:"2_5_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_5_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_5_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_5_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_5_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:6,
                name: "有入睡困难或睡眠浅或夜间易醒，多梦",
                selects:[
                {
                    key:"2_6_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_6_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_6_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_6_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_6_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:7,
                name: "容易有头晕、心慌、眩晕的感觉",
                selects:[
                {
                    key:"2_7_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_7_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_7_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_7_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_7_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:8,
                name: "尿色深，时间短且少",
                selects:[
                {
                    key:"2_8_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_8_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_8_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_8_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_8_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:9,
                name: "容易出现口腔溃疡，溃疡位置多生于舌部",
                selects:[
                {
                    key:"2_9_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_9_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_9_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_9_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_9_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:10,
                name: ".面色苍白，缺血缺铁",
                selects:[
                {
                    key:"2_10_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_10_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_10_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_10_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_10_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:11,
                name: "喜欢社交，以结交朋友为乐趣",
                selects:[
                {
                    key:"2_11_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_11_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_11_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_11_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_11_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:12,
                name: "容易心烦或心烦时后背疼痛",
                selects:[
                {
                    key:"2_12_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_12_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_12_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_12_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_12_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:13,
                name: "特别怕热，夏天喜欢吹空调、喝冷饮",
                selects:[
                {
                    key:"2_13_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_13_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_13_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_13_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_13_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:14,
                name: "家族有糖尿病或白血病的遗传史（家族史指双亲、祖父母、外祖父母、兄弟姐妹以及子女的健康情况，“无”选0分，”有“按照本人是否患病及患病严重程度填写）",
                selects:[
                {
                    key:"2_14_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_14_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_14_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_14_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_14_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:15,
                name: "喜欢吃辣的，或经常感到口渴",
                selects:[
                {
                    key:"2_15_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_15_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_15_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_15_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_15_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:16,
                name: "皮肤红血丝明显，或容易长肉赘（如瘊子、疣等）",
                selects:[
                {
                    key:"2_16_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_16_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_16_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_16_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_16_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:17,
                name: "声音洪亮，底气充沛（大嗓门）",
                selects:[
                {
                    key:"2_17_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_17_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_17_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_17_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_17_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:18,
                name: "运动时容易大汗淋漓，衣服上有出汗后的白印",
                selects:[
                {
                    key:"2_18_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_18_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_18_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_18_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_18_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:19,
                name: "喜欢看笑话，听相声，欣赏幽默的人",
                selects:[
                {
                    key:"2_19_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_19_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_19_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_19_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_19_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:20,
                name: "常有神志不宁，精神萎顿",
                selects:[
                {
                    key:"2_20_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"2_20_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"2_20_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"2_20_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"2_20_4",
                    value:"5、总是(4分)"
                }]
              }
            ],
              fen:0
            },
            {
              groupId:3,
              name:"第三部分",
              questions:[
                {
                questioId:1,
                name: "有消化不良的症状或慢性胃炎或慢性肠炎病史",
                selects:[
                {
                    key:"3_1_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_1_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_1_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_1_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_1_4",
                    value:"5、总是(4分)"
                }]
              },
              
              {
                questioId:2,
                name: "容易胡思乱想，杞人忧天",
                selects:[
                {
                    key:"3_2_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_2_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_2_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_2_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_2_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:3,
                name: "面色暗沉，没有光泽",
                selects:[
                {
                    key:"3_3_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_3_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_3_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_3_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_3_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:4,
                name: "口唇颜色苍白或暗淡无色",
                selects:[
                {
                    key:"3_4_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_4_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_4_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_4_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_4_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:5,
                name: "疲倦，说话虚弱无力",
                selects:[
                {
                    key:"3_5_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_5_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_5_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_5_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_5_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:6,
                name: "身体有浮肿或肥胖，肌肉疏松，脂肪下垂",
                selects:[
                {
                    key:"3_6_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_6_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_6_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_6_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_6_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:7,
                name: "形体消瘦，吃很多也不胖",
                selects:[
                {
                    key:"3_7_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_7_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_7_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_7_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_7_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:8,
                name: "睡觉的时候容易流口水而自己不知道",
                selects:[
                {
                    key:"3_8_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_8_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_8_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_8_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_8_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:9,
                name: "没有食欲，即使是自己喜欢吃的也没有胃口",
                selects:[
                {
                    key:"3_9_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_9_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_9_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_9_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_9_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:10,
                name: "吃东西后不易消化，常有肚子不舒服，有饱胀感，容易打嗝",
                selects:[
                {
                    key:"3_10_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_10_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_10_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_10_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_10_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:11,
                name: "喜欢吃甜食，一看见甜点就控制不住自己",
                selects:[
                {
                    key:"3_11_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_11_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_11_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_11_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_11_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:12,
                name: "每年的夏秋之际容易得急性肠炎",
                selects:[
                {
                    key:"3_12_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_12_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_12_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_12_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_12_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:13,
                name: "身体里有湿气，容易烂脚或有脚气或灰指甲",
                selects:[
                {
                    key:"3_13_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_13_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_13_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_13_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_13_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:14,
                name: ".口腔里有味道或容易得虫牙",
                selects:[
                {
                    key:"3_14_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_14_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_14_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_14_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_14_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:15,
                name: "皮肤比较厚或粗糙，肤色发黄",
                selects:[
                {
                    key:"3_15_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_15_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_15_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_15_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_15_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:16,
                name: "答应别人的事情就一定要做到，否则心不安",
                selects:[
                {
                    key:"3_16_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_16_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_16_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_16_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_16_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:17,
                name: "嘴唇上有暗色的色素沉着",
                selects:[
                {
                    key:"3_17_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_17_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_17_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_17_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_17_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:18,
                name: "认真负责时身体有更大的潜能，比如加班、出差",
                selects:[
                {
                    key:"3_18_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_18_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_18_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_18_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_18_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:19,
                name: "容易闹肚子，吃抗菌药也不管用",
                selects:[
                {
                    key:"3_19_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_19_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_19_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_19_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_19_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:20,
                name: "会无缘无故就记忆力下降，记不住事情",
                selects:[
                {
                    key:"3_20_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"3_20_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"3_20_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"3_20_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"3_20_4",
                    value:"5、总是(4分)"
                }]
              }
            ],
              fen:0
            },
            {
              groupId:4,
              name:"第四部分",
              questions:[
                {
                questioId:1,
                name: "从小就容易得感冒，感冒不容易好",
                selects:[
                {
                    key:"4_1_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_1_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_1_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_1_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_1_4",
                    value:"5、总是(4分)"
                }]
              },
              
              {
                questioId:2,
                name: "容易陷入到忧伤的情绪中，整日郁郁寡欢",
                selects:[
                {
                    key:"4_2_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_2_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_2_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_2_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_2_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:3,
                name: "有呼吸短促，感觉气不够用",
                selects:[
                {
                    key:"4_3_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_3_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_3_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_3_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_3_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:4,
                name: "皮肤上的汗毛萎黄、枯槁",
                selects:[
                {
                    key:"4_4_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_4_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_4_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_4_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_4_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:5,
                name: "有鼻炎、咽炎或者慢性支气管炎病史（“无”选0分，”有“按照患病严重程度填写）",
                selects:[
                {
                    key:"4_5_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_5_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_5_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_5_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_5_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:6,
                name: "一遇到凉的空气就立即起鸡皮疙瘩",
                selects:[
                {
                    key:"4_6_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_6_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_6_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_6_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_6_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:7,
                name: "皮肤比较薄，容易过敏或有痤疮",
                selects:[
                {
                    key:"4_7_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_7_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_7_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_7_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_7_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:8,
                name: "容易便秘或有痔疮",
                selects:[
                {
                    key:"4_8_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_8_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_8_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_8_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_8_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:9,
                name: "天气变化容易打喷嚏、流鼻涕",
                selects:[
                {
                    key:"4_9_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_9_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_9_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_9_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_9_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:10,
                name: ".家族中有肺结核的遗传史（家族史指双亲、祖父母、外祖父母、兄弟姐妹以及子女的健康情况，“无”选0分，”有“按照本人是否患病及患病严重程度填写）",
                selects:[
                {
                    key:"4_10_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_10_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_10_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_10_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_10_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:11,
                name: "喜欢闻芳香的味道，比如芳香精油",
                selects:[
                {
                    key:"4_11_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_11_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_11_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_11_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_11_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:12,
                name: ".皮肤怕干燥，干燥时情绪也会烦躁",
                selects:[
                {
                    key:"4_12_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_12_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_12_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_12_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_12_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:13,
                name: "有洁癖，强迫自己和别人洗衣服、洗澡",
                selects:[
                {
                    key:"4_13_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_13_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_13_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_13_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_13_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:14,
                name: "家庭关系紧张，喜欢别人无条件听自己的",
                selects:[
                {
                    key:"4_14_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_14_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_14_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_14_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_14_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:15,
                name: "鼻子容易干燥，甚至流鼻血",
                selects:[
                {
                    key:"4_15_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_15_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_15_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_15_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_15_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:16,
                name: "压力太大时容易悲观和放弃",
                selects:[
                {
                    key:"4_16_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_16_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_16_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_16_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_16_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:17,
                name: "喜欢吃白色食物，比如银耳、莲子、百合",
                selects:[
                {
                    key:"4_17_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_17_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_17_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_17_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_17_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:18,
                name: "有颈椎病病史（“无”选0分，”有“按照患病严重程度填写）",
                selects:[
                {
                    key:"4_18_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_18_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_18_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_18_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_18_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:19,
                name: "喜欢吃走窜的味道，比如吃芥末",
                selects:[
                {
                    key:"4_19_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_19_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_19_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_19_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_19_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:20,
                name: "崇拜有气魄、代表正义的人物，排斥邪恶的力量",
                selects:[
                {
                    key:"4_20_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"4_20_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"4_20_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"4_20_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"4_20_4",
                    value:"5、总是(4分)"
                }]
              }
            ],
              fen:0
            },
            {
              groupId:5,
              name:"第五部分",
              questions:[
                {
                questioId:1,
                name: "容易腰疼，或膝关节酸软无力",
                selects:[
                {
                    key:"5_1_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_1_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_1_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_1_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_1_4",
                    value:"5、总是(4分)"
                }]
              },
              
              {
                questioId:2,
                name: "牙齿松动易脱落",
                selects:[
                {
                    key:"5_2_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_2_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_2_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_2_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_2_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:3,
                name: "容易脱发，头发稀疏",
                selects:[
                {
                    key:"5_3_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_3_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_3_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_3_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_3_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:4,
                name: "感觉口干，缺少津液",
                selects:[
                {
                    key:"5_4_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_4_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_4_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_4_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_4_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:5,
                name: "听声音不顺畅，反应不灵敏或有耳鸣",
                selects:[
                {
                    key:"5_5_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_5_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_5_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_5_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_5_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:6,
                name: "不喜欢激烈运动，喜欢久坐不动",
                selects:[
                {
                    key:"5_6_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_6_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_6_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_6_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_6_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:7,
                name: "劳累时耳朵发热",
                selects:[
                {
                    key:"5_7_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_7_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_7_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_7_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_7_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:8,
                name: "手脚冰冷",
                selects:[
                {
                    key:"5_8_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_8_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_8_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_8_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_8_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:9,
                name: "一咳嗽就遗尿",
                selects:[
                {
                    key:"5_9_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_9_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_9_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_9_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_9_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:10,
                name: "胆小，总感到害怕，担心出现麻烦",
                selects:[
                {
                    key:"5_10_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_10_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_10_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_10_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_10_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:11,
                name: "夜尿次数多？",
                selects:[
                {
                    key:"5_11_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_11_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_11_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_11_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_11_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:12,
                name: "比起炎热的夏天，更耐受寒冷的冬天",
                selects:[
                {
                    key:"5_12_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_12_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_12_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_12_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_12_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:13,
                name: "疲劳以后容易脚后跟疼",
                selects:[
                {
                    key:"5_13_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_13_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_13_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_13_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_13_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:14,
                name: "害怕听鬼故事，看恐怖电影",
                selects:[
                {
                    key:"5_14_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_14_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_14_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_14_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_14_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:15,
                name: "在感情上有依赖心",
                selects:[
                {
                    key:"5_15_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_15_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_15_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_15_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_15_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:16,
                name: "容易溺爱孩子或者养宠物",
                selects:[
                {
                    key:"5_16_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_16_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_16_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_16_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_16_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:17,
                name: "喜欢怀旧，和人吵架容易翻老账",
                selects:[
                {
                    key:"5_17_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_17_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_17_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_17_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_17_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:18,
                name: "一委屈就哭",
                selects:[
                {
                    key:"5_18_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_18_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_18_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_18_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_18_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:19,
                name: "有酒精过瘾的倾向",
                selects:[
                {
                    key:"5_19_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_19_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_19_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_19_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_19_4",
                    value:"5、总是(4分)"
                }]
              },
              {
                questioId:20,
                name: "容易恐惧，缺乏安全感",
                selects:[
                {
                    key:"5_20_0",
                    value:"1、从不(0分)"
                },
                {
                    key:"5_20_1",
                    value:"2、很少(1分)"
                },
                {
                    key:"5_20_2",
                    value:"3、有时(2分)"
                },
                {
                    key:"5_20_3",
                    value:"4、经常(3分)"
                },
                {
                    key:"5_20_4",
                    value:"5、总是(4分)"
                }]
              }
            ],
              fen:0
            }
        ]
      }
    }
  }
  return ret

}